### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by LatusPL** [TeamPBCN/pmftools#4]
I don't know why these weren't included but They need to be placed in tools folder to make the converter work
![image](https://github.com/TeamPBCN/pmftools/assets/112699360/ddd1897c-2f8e-42bb-9a70-c3969dbc3b00)
![image](https://github.com/TeamPBCN/pmftools/assets/112699360/4e8bfedb-0c13-4199-bfc7-7fc50caa0e6e)
![image](https://github.com/TeamPBCN/pmftools/assets/112699360/c6ed6aeb-35ce-43ea-8632-a10cd4c153a8)

**Comment by LatusPL** [comment]
Sorry if the language is not English but it says its missing these .dll

- msys-stc++-6.dll
- msys-gcc_s-seh-1.dll
- msys-2.0.dll

**Comment by LITTOMA** [comment]
You need to install msys2 to run this program.

**Comment by andymage593** [comment]
I have already installed msys2，I tried using PMF to MP4 converter.However, an error still occurs.
https://www.msys2.org/

![Image](https://github.com/user-attachments/assets/f1933e6d-6aa3-41d5-b905-6f30f3533819)

**Comment by andymage593** [comment]
Processing file input\pmf\0C959EA2.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 000002dd5568ba80] cabac decode of qscale diff failed at 22 6
[h264 @ 000002dd5568ba80] error while decoding MB 22 6, bytestream -8
obj\0C959EA2.oma: No such file or directory
Processing file input\pmf\0F67701F.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 000001854461ba80] error while decoding MB 28 8, bytestream -7
obj\0F67701F.oma: No such file or directory
Processing file input\pmf\215DDB9C.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 000001bd1df8ba80] error while decoding MB 6 10, bytestream -8
obj\215DDB9C.oma: No such file or directory
Processing file input\pmf\3290773D.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 000002eea922ba80] error while decoding MB 25 10, bytestream -13
obj\3290773D.oma: No such file or directory
Processing file input\pmf\4E887BDE.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 000001ce9727ba80] error while decoding MB 12 9, bytestream -6
obj\4E887BDE.oma: No such file or directory
Processing file input\pmf\74E1E0A6.pmf...
obj\74E1E0A6.oma: No such file or directory
Processing file input\pmf\D1328B57.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 0000020be17dba80] cabac decode of qscale diff failed at 2 10
[h264 @ 0000020be17dba80] error while decoding MB 2 10, bytestream -12
obj\D1328B57.oma: No such file or directory
Processing file input\pmf\D3F9FDA5.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
[h264 @ 000001ec29d5ba80] cabac decode of qscale diff failed at 2 10
[h264 @ 000001ec29d5ba80] error while decoding MB 2 10, bytestream -12
obj\D3F9FDA5.oma: No such file or directory
Processing file input\pmf\D9A9EFF7.pmf...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at VGMToolbox.format.MpegStream.DemultiplexStreams(DemuxOptionsStruct demuxOptions)
   at psmfdump.Program.DumpPsmf(String path, String videoPath, String audioPath)
   at psmfdump.Program.Main(String[] args)
